[[fish]]
name = "Neptuna"
conditions = [
    {}
]

[[fish]]
name = "Jellyfish"
conditions = [
    { water_location = ["river"], season = ["spring", "summer"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Tropical Fish"
conditions = [ 
    { water_location = ["ocean"], season = ["spring"], time_of_day = ["night"], dimension = ["overworld"] },
    { water_location = ["ocean"], season = ["summer"], dimension = ["overworld"] }
]

[[fish]]
name = "Drooping Gourami"
conditions = [
    { water_location = ["ocean"], season = ["spring"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Atlantic Halibut"
conditions = [
    { water_location = ["ocean"], season = ["spring"], time_of_day = ["day"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Spindlefish"
conditions = [
    { water_location = ["ocean"], season = ["spring"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Pufferfish"
conditions = [
    { water_location = ["ocean"], season = ["spring", "summer", "autumn"], time_of_day = ["night"], weather = ["clear"], dimension = ["overworld"] }
]

[[fish]]
name = "Minnow"
conditions = [
    { water_location = ["fresh", "river"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Bluegill"
conditions = [
    { water_location = ["fresh", "river"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Perch"
conditions = [
    { water_location = ["fresh"], season = ["spring", "autumn"], time_of_day = ["day"], dimension = ["overworld"] },
    { water_location = ["fresh"], season = ["winter"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Carp"
conditions = [
    { water_location = ["fresh"], season = ["spring"], time_of_day = ["day"], weather = ["rain"], dimension = ["overworld"] },
    { water_location = ["fresh"], season = ["summer", "autumn"], time_of_day = ["day"], dimension = ["overworld"] },
    { water_location = ["fresh"], season = ["winter"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Beaked Herring"
conditions = [
    { water_location = ["fresh"], season = ["spring"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Hatchetfish"
conditions = [
    { water_location = ["fresh"], season = ["spring", "winter"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Eyelash"
conditions = [
    { water_location = ["fresh"], season = ["spring"], time_of_day = ["night"], weather = ["clear"], dimension = ["overworld"] }
]

[[fish]]
name = "Smallmouth Bass"
conditions = [
    { water_location = ["river"], season = ["spring"], time_of_day = ["night"], dimension = ["overworld"] },
    { water_location = ["river"], season = ["summer"], dimension = ["overworld"] },
    { water_location = ["river"], season = ["autumn"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Cod"
conditions = [
    { water_location = ["river"], season = ["spring"], time_of_day = ["night"], dimension = ["overworld"] },
    { water_location = ["river"], season = ["winter"], dimension = ["overworld"] }
]

[[fish]]
name = "Pink Salmon"
conditions = [
    { water_location = ["river"], season = ["spring"], time_of_day = ["night"], dimension = ["overworld"] },
    { water_location = ["river"], season = ["winter"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Catfish"
conditions = [
    { water_location = ["river"], season = ["spring"], time_of_day = ["night"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Bayad"
conditions = [
    { water_location = ["river"], season = ["spring"], time_of_day = ["night"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Blind Sailfin"
conditions = [
    { water_location = ["river"], season = ["spring"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Sneep Snorp"
conditions = [
    { water_location = ["ocean"], season = ["summer"], time_of_day = ["day", "night"], dimension = ["overworld"] }
]

[[fish]]
name = "Red Grouper"
conditions = [
    { water_location = ["ocean"], season = ["summer"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Tuna"
conditions = [
    { water_location = ["ocean"], season = ["summer"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Capitaine"
conditions = [
    { water_location = ["ocean"], season = ["summer"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Goldfish"
conditions = [
    { water_location = ["ocean"], season = ["summer"], time_of_day = ["day"], weather = ["clear"], dimension = ["overworld"] }
]

[[fish]]
name = "Leech"
conditions = [
    { water_location = ["freshwater", "river"], season = ["summer"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Piranha"
conditions = [
    { water_location = ["freshwater"], season = ["summer"], time_of_day = ["night"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Boulti"
conditions = [
    { water_location = ["freshwater"], season = ["summer"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Arapaima"
conditions = [
    { water_location = ["freshwater"], season = ["summer"], time_of_day = ["day"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Circus Fish"
conditions = [
    { water_location = ["freshwater"], season = ["summer"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Salmon"
conditions = [
    { water_location = ["river"], season = ["summer", "autumn"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Synodontis"
conditions = [
    { water_location = ["river"], season = ["summer"], time_of_day = ["day"], weather = ["clear"], dimension = ["overworld"] }
]

[[fish]]
name = "Tambaqui"
conditions = [
    { water_location = ["river"], season = ["summer"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Box Turtle"
conditions = [
    { water_location = ["river"], season = ["summer"], time_of_day = ["night"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Blackfish"
conditions = [
    { water_location = ["ocean"], season = ["autumn"], time_of_day = ["night"], dimension = ["overworld"] },
    { water_location = ["ocean"], season = ["winter"], dimension = ["overworld"] }
]

[[fish]]
name = "Picklefish"
conditions = [
    { water_location = ["ocean"], season = ["autumn"], time_of_day = ["night"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Forkfish"
conditions = [
    { water_location = ["ocean"], season = ["autumn"], dimension = ["overworld"] }
]

[[fish]]
name = "Sailor Barb"
conditions = [
    { water_location = ["ocean"], season = ["autumn"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Demon Herring"
conditions = [
    { water_location = ["ocean"], season = ["autumn"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Copperflame Anthias"
conditions = [
    { water_location = ["ocean"], season = ["autumn", "winter"], time_of_day = ["night"], weather = ["clear"], dimension = ["overworld"] }
]

[[fish]]
name = "Red Shrooma"
conditions = [
    { water_location = ["ocean"], season = ["autumn"], time_of_day = ["day"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Gar"
conditions = [
    { water_location = ["fresh"], season = ["autumn"], time_of_day = ["day"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Bark Angelfish"
conditions = [
    { water_location = ["fresh"], season = ["autumn"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Amber Goby"
conditions = [
    { water_location = ["fresh"], season = ["autumn"], time_of_day = ["night"], weather = ["clear"], dimension = ["overworld"] }
]

[[fish]]
name = "Brown Trout"
conditions = [
    { water_location = ["river"], season = ["autumn", "winter"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Muskellenge"
conditions = [
    { water_location = ["river"], season = ["autumn"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Arrau Turtle"
conditions = [
    { water_location = ["river"], season = ["autumn"], time_of_day = ["night"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Pollock"
conditions = [
    { water_location = ["ocean"], season = ["winter"], time_of_day = ["day"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Atlantic Cod"
conditions = [
    { water_location = ["ocean"], season = ["winter"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Triple Twirl Pleco"
conditions = [
    { water_location = ["ocean"], season = ["winter"], time_of_day = ["night"], dimension = ["overworld"] }
]

[[fish]]
name = "Pacific Halibut"
conditions = [
    { water_location = ["ocean"], season = ["winter"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Brown Shrooma"
conditions = [
    { water_location = ["ocean"], season = ["winter"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Frosty Fin"
conditions = [
    { water_location = ["fresh"], season = ["winter"], time_of_day = ["night"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Aero Mono"
conditions = [
    { water_location = ["fresh"], season = ["winter"], time_of_day = ["day"], dimension = ["overworld"] }
]

[[fish]]
name = "Duality Damselfish"
conditions = [
    { water_location = ["river"], season = ["winter"], time_of_day = ["night"], weather = ["clear"], dimension = ["overworld"] }
]

[[fish]]
name = "Rainbow Trout"
conditions = [
    { water_location = ["river"], season = ["winter"], time_of_day = ["day"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Starshell Turtle"
conditions = [
    { water_location = ["river"], season = ["winter"], time_of_day = ["night"], weather = ["rain"], dimension = ["overworld"] }
]

[[fish]]
name = "Searing Cod"
conditions = [
    { dimension = ["nether"] }
]

[[fish]]
name = "Lava Pufferfish"
conditions = [
    { dimension = ["nether"] }
]

[[fish]]
name = "Fortress Grouper"
conditions = [
    { dimension = ["nether"] }
]

[[fish]]
name = "Blazefish"
conditions = [
    { dimension = ["nether"] }
]

[[fish]]
name = "Obsidianfish"
conditions = [
    { dimension = ["nether"], biome = ["basalt deltas"] }
]

[[fish]]
name = "Magmacube Fish"
conditions = [
    { dimension = ["nether"], biome = ["basalt deltas"] }
]

[[fish]]
name = "Glowdine"
conditions = [
    { dimension = ["nether"], biome = ["warped forest"] }
]

[[fish]]
name = "Eyeball Fish"
conditions = [
    { dimension = ["nether"], biome = ["crimson forest"] }
]

[[fish]]
name = "Bonefish"
conditions = [
    { dimension = ["nether"], biome = ["nether wastes"] }
]

[[fish]]
name = "Wither Bonefish"
conditions = [
    { dimension = ["nether"], biome = ["soul sand valley"] }
]

[[fish]]
name = "Soul Sucker"
conditions = [
    { dimension = ["nether"], biome = ["soul sand valley"] }
]